---
Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
ZapInjector:
  - Strategy: ZapInjector.Strategies.LoadAllServicesFromAssembliesWithConventionStrategy,
      ZapInjector
    Configuration:
      Assemblies:
        - ZapInjector.Examples.Main
        - ZapInjector.Examples.Abstractions
        - ZapInjector.Examples.Implementations
      Convention: ZapInjector.Strategies.Conventions.LoadAllServicesFromAssembliesDefaultConvention,
        ZapInjector
  - Strategy: ZapInjector.Strategies.LoadServicesFromExplicitSettingsStrategy, ZapInjector
    Configuration:
      Values:
        - Name: annasName
          Value: Anna
          Type: System.String
      ServiceDescriptions:
        - ServiceType: ZapInjector.Examples.Abstractions.INameAbstraction, ZapInjector.Examples.Abstractions
          ImplementationType: ZapInjector.Examples.ImplementationsTwo.NameImplementationThree,
            ZapInjector.Examples.ImplementationsTwo
          ServiceLifetime: Singleton
        - ServiceType: ZapInjector.Examples.Abstractions.INameAbstraction, ZapInjector.Examples.Abstractions
          ImplementationType: ZapInjector.Examples.ImplementationsTwo.NameImplementationFour,
            ZapInjector.Examples.ImplementationsTwo
          Dependencies:
            - Value:
                Value: Nick
                Type: System.String
          ServiceLifetime: Singleton
        - ServiceType: ZapInjector.Examples.Abstractions.INameAbstraction, ZapInjector.Examples.Abstractions
          ImplementationFactory:
            InstanceType: ZapInjector.Examples.Abstractions.INameAbstraction, ZapInjector.Examples.Abstractions
            StaticReference: ZapInjector.Examples.ImplementationsTwo.NameImplementationFour,
              ZapInjector.Examples.ImplementationsTwo
            Method:
              MethodName: Create
              Parameters:
                - Value:
                    Value: Taylor
                    Type: System.String
          ServiceLifetime: Singleton
        - ServiceType: ZapInjector.Examples.Abstractions.INameAbstraction, ZapInjector.Examples.Abstractions
          ImplementationType: ZapInjector.Examples.ImplementationsTwo.NameImplementationFour,
            ZapInjector.Examples.ImplementationsTwo
          Dependencies:
            - Value:
                Value: Anna
                Type: System.String
          OnAfterCreate:
            - MethodName: ChangeName
              Parameters:
                - Value:
                    Value: Claire
                    Type: System.String
          ServiceLifetime: Singleton
        - ServiceType: ZapInjector.Examples.Abstractions.INameAbstraction, ZapInjector.Examples.Abstractions
          ImplementationFactory:
            InstanceType: ZapInjector.Examples.Abstractions.INameAbstraction, ZapInjector.Examples.Abstractions
            StaticReference: ZapInjector.Examples.ImplementationsTwo.NameImplementationFour,
              ZapInjector.Examples.ImplementationsTwo
            Method:
              MethodName: Create
              Parameters:
                - Value:
                    Value: Jhon
                    Type: System.String
          OnAfterCreate:
            - MethodName: ChangeName
              Parameters:
                - Value:
                    Value: Johan
                    Type: System.String
          ServiceLifetime: Singleton
        - ServiceType: ZapInjector.Examples.Abstractions.INameAbstraction, ZapInjector.Examples.Abstractions
          ImplementationType: ZapInjector.Examples.ImplementationsTwo.NameImplementationFour, ZapInjector.Examples.ImplementationsTwo
          Dependencies:
            - Reference:
                Name: annasName
          ServiceLifetime: Singleton
AllowedHosts: "*"
